import Head from "next/head"

export default function Home() {
    return (
        <div className="root">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="container">
                <div className="header">
                    <h1 className="title">
                        CRUD <a href="https://nextjs.org">Oversigt</a>
                    </h1>
                </div>
                <div className="user-list">
                  <ul className="list">
                    <li className="user-item">
                      
                    </li>
                  </ul>
                </div>
            </main>
        </div>
    )
}
