import React, { useState } from 'react';
import Head from "next/head"

// Components
import DeleteModal from '../components/deleteModal';
import CreateModal from '../components/createModal';
import EditModal from '../components/editModal';
import UserList from '../components/userList';

export default function Home() {

    const [isDeleteOpen, setIsDeleteOpen] = useState(null);
    const [isCreateOpen, setIsCreateOpen] = useState(null);
    const [isEditOpen, setIsEditOpen] = useState(null);

    return (
        <>
            <div className="root">
                <Head>
                    <title>CRUD Oversigt</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className="container">
                    <div className="header">
                        <h1 className="title">
                            CRUD <span>Oversigt</span>
                        </h1>
                    </div>
                    <button className="btn btn-create" onClick={(e) => setIsCreateOpen(true)}>
                        Create user &#43;
                    </button>
                    <div className="user-list">
                        <UserList setIsEditOpen={setIsEditOpen} setIsDeleteOpen={setIsDeleteOpen} />
                    </div>
                </main>
            </div>

            <DeleteModal isOpen={isDeleteOpen} setIsOpen={setIsDeleteOpen} />
            <CreateModal isOpen={isCreateOpen} setIsOpen={setIsCreateOpen} />
            <EditModal isOpen={isEditOpen} setIsOpen={setIsEditOpen} />

        </>
    )
}
